sudo: false
language: ruby
before_install:
  - gem update --system
  - gem install bundler
jdk:
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
rvm:
  - jruby-9.2.5.0
env:
  - JRUBY_OPTS=--debug

script: rake install_jars && rake 

branches:
  only:
    - public
