sudo: false
language: ruby
before_install:
  - gem update --system
  - gem install bundler --no-ri --no-rdoc
jdk:
  - oraclejdk9
  - openjdk10
  - oraclejdk11
rvm:
  - jruby-9.2.5.0
env:
  - JRUBY_OPTS=--debug

script: rake install_jars && rake 

branches:
  only:
    - public
